---
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456


  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    prefix: classpath:/templates/
    content-type: text/html
    suffix: .html
    encoding: UTF-8

  session:
    store-type: none

server:
  port: 80
  contextPath: /ndcf

